In [1]:
import numpy as np
import gzip # This is used in extracting the images

import matplotlib.pyplot as plt # in order to plot the images to see what we are dealing with
from sklearn.ensemble import RandomForestClassifier # you'll be using Random Forest to classify the images
from sklearn.metrics import accuracy_score # sklearn's way of measuring accuracy
from sklearn.metrics import classification_report 

%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.misc import imread
from wordcloud import WordCloud, STOPWORDS
from nltk.corpus import stopwords 

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.offline as py
import plotly.graph_objs as go
import plotly.tools as tls
from bs4 import BeautifulSoup

import string
from string import digits
from nltk.tokenize import word_tokenize, TreebankWordTokenizer
from nltk import SnowballStemmer, PorterStemmer, LancasterStemmer
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder


from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import learning_curve
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from nltk.stem import WordNetLemmatizer

class color:
     BOLD = '\033[1m'
     UNDERLINE = '\033[4m'
     END = '\033[0m'

In [3]:
solution = pd.read_csv('sample_submission.csv')
solution.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [4]:
solution.shape

(28000, 2)

In [ ]:
train = pd.read_csv('train.csv')
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [8]:
test = pd.read_csv('test.csv')
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [9]:
train.shape, test.shape

((42000, 785), (28000, 784))

In [ ]:
#Plotting

In [10]:
X = train.drop('label', axis = 1)
y = train['label']

In [191]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2,random_state = 42, shuffle = False)

In [32]:
# X_train = (X_tr-np.min(X_tr))/(np.max(X_tr)-np.min(X_tr))
# X_test = (X_te-np.min(X_te))/(np.max(X_te)-np.min(X_te))

In [33]:
# #image_index = 1 ## Change me to view different images

# print("Label: ", y_train[1])
# reshaped_image = X_train[1].reshape((28, 28))

# plt.imshow(reshaped_image, cmap='gray')
# plt.show()

# LogisticRegression

In [45]:
LRmodel = LogisticRegression( C=100,  random_state=0)

In [46]:
LRmodel.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning:

Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.



LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
pred_lm = LRmodel.predict(X_test)
pred_lm

array([0, 7, 7, ..., 7, 6, 9], dtype=int64)

In [48]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test, pred_lm)))
print('Precision: '+ str( metrics.precision_score(y_test, pred_lm, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test, pred_lm, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test, pred_lm, average='macro')))

Accuracy: 0.9125
Precision: 0.9116236373826532
Recall: 0.9106895064656231
F1_Score: 0.9109708479193118


In [49]:
print(metrics.classification_report(y_test, pred_lm))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       852
           1       0.94      0.97      0.95       950
           2       0.89      0.88      0.88       801
           3       0.88      0.89      0.89       882
           4       0.92      0.92      0.92       811
           5       0.91      0.84      0.88       747
           6       0.94      0.96      0.95       831
           7       0.93      0.94      0.93       884
           8       0.87      0.88      0.87       802
           9       0.89      0.87      0.88       840

   micro avg       0.91      0.91      0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400



In [50]:
metrics.confusion_matrix(y_test, pred_lm)

array([[817,   0,   9,   3,   1,   3,  10,   1,   7,   1],
       [  1, 920,   3,   6,   1,   2,   1,   2,  12,   2],
       [ 11,  11, 703,  17,   7,   2,  12,   9,  24,   5],
       [  4,   5,  28, 784,   4,  19,   5,  10,  13,  10],
       [  3,   8,   7,   1, 743,   4,   7,   2,  11,  25],
       [  5,   4,   9,  35,  10, 631,  12,   4,  26,  11],
       [  6,   2,  10,   0,   3,   5, 800,   0,   4,   1],
       [  2,   1,  11,   4,   8,   2,   2, 830,   3,  21],
       [  5,  23,   8,  21,   7,  16,   2,   4, 706,  10],
       [  3,   6,   5,  15,  27,  10,   0,  33,  10, 731]], dtype=int64)

In [51]:
y_pred_TK = LRmodel.predict(test)
y_pred_TK

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [52]:
df_lm = pd.DataFrame({"ImageId":solution['ImageId'], "Label":y_pred_TK})
df_lm.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      7
4        5      3

In [53]:
df_lm.shape

(28000, 2)

In [54]:
df_lm.to_csv('lmC_attempt1.csv', index = False) #0.90385

# RandomClassifier

In [224]:
RFmodel = RandomForestClassifier(random_state = 42, n_estimators=200, n_jobs = -1)

In [225]:
RFmodel.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [226]:
pred_rf = RFmodel.predict(X_test)
pred_rf

array([0, 7, 7, ..., 7, 6, 9], dtype=int64)

In [227]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test, pred_rf)))
print('Precision: '+ str( metrics.precision_score(y_test, pred_rf, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test, pred_rf, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test, pred_rf, average='macro')))
#print('R/A_Score: '+ str( metrics.roc_auc_score(y_test, pred_rf)))

Accuracy: 0.9688095238095238
Precision: 0.9686043100955175
Recall: 0.9685290646876945
F1_Score: 0.9685378234926288


In [ ]:
random state:42
    
    Accuracy: 0.9422619047619047
Precision: 0.9414387860845211
Recall: 0.941038948260065
F1_Score: 0.94110167348572
    
    rand = 42, n-est = 100
    
Accuracy: 0.9680952380952381
Precision: 0.9678412846357054
Recall: 0.9677974516938548
F1_Score: 0.9677934246529898
    
    rand = 42, n-est = 200   
Accuracy: 0.9688095238095238
Precision: 0.9686043100955175
Recall: 0.9685290646876945
F1_Score: 0.9685378234926288

In [228]:
print(metrics.classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       852
           1       0.98      0.99      0.98       950
           2       0.96      0.97      0.97       801
           3       0.97      0.95      0.96       882
           4       0.97      0.97      0.97       811
           5       0.97      0.96      0.97       747
           6       0.97      0.99      0.98       831
           7       0.98      0.97      0.98       884
           8       0.95      0.96      0.95       802
           9       0.96      0.94      0.95       840

   micro avg       0.97      0.97      0.97      8400
   macro avg       0.97      0.97      0.97      8400
weighted avg       0.97      0.97      0.97      8400



In [229]:
metrics.confusion_matrix(y_test, pred_rf)

array([[839,   0,   0,   0,   0,   1,   6,   0,   6,   0],
       [  0, 937,   2,   3,   2,   1,   1,   1,   3,   0],
       [  7,   0, 777,   2,   2,   1,   2,   2,   7,   1],
       [  1,   1,  14, 840,   0,   7,   1,   6,   8,   4],
       [  1,   2,   1,   0, 784,   0,   7,   0,   3,  13],
       [  1,   1,   0,  11,   1, 720,   4,   0,   6,   3],
       [  4,   2,   0,   0,   3,   2, 819,   0,   1,   0],
       [  0,   2,   7,   1,   1,   0,   0, 861,   3,   9],
       [  1,  10,   1,   1,   3,   6,   3,   1, 769,   7],
       [  6,   4,   5,  10,   9,   1,   0,   8,   5, 792]], dtype=int64)

In [230]:
y_pred_RF = RFmodel.predict(test)
y_pred_RF

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [231]:
df_rf = pd.DataFrame({"ImageId":solution['ImageId'], "Label":y_pred_RF})
df_rf.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [232]:
df_rf.shape

(28000, 2)

In [233]:
df_rf.to_csv('rf_r42_n200.csv', index = False) #0.93800 #rf_r42_n100 = 0.96314

In [235]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, log_loss
from sklearn.svm import SVC

In [236]:
svc = SVC(kernel='rbf')


In [237]:
svc.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning:

The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [238]:
y_pred = svc.predict(X_test)


In [239]:
print("The accuracy score of the SVC is:", accuracy_score(y_test, y_pred))
print("\n\nClassification Report:\n\n",classification_report(y_test, y_pred))

The accuracy score of the SVC is: 0.1130952380952381


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.





Classification Report:

               precision    recall  f1-score   support

           0       0.00      0.00      0.00       852
           1       0.11      1.00      0.20       950
           2       0.00      0.00      0.00       801
           3       0.00      0.00      0.00       882
           4       0.00      0.00      0.00       811
           5       0.00      0.00      0.00       747
           6       0.00      0.00      0.00       831
           7       0.00      0.00      0.00       884
           8       0.00      0.00      0.00       802
           9       0.00      0.00      0.00       840

   micro avg       0.11      0.11      0.11      8400
   macro avg       0.01      0.10      0.02      8400
weighted avg       0.01      0.11      0.02      8400

