In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.misc import imread
from wordcloud import WordCloud, STOPWORDS
from nltk.corpus import stopwords 

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.offline as py
import plotly.graph_objs as go
import plotly.tools as tls
from bs4 import BeautifulSoup

import string
from string import digits
from nltk.tokenize import word_tokenize, TreebankWordTokenizer
from nltk import SnowballStemmer, PorterStemmer, LancasterStemmer
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder


from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import learning_curve
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB


class color:
     BOLD = '\033[1m'
     UNDERLINE = '\033[4m'
     END = '\033[0m'

In [3]:
subm = pd.read_csv('gender_submission.csv')
subm.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [4]:
train = pd.read_csv('train.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
test = pd.read_csv('test.csv')
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
subm.shape, train.shape, test.shape

((418, 2), (891, 12), (418, 11))

In [7]:
test['Survived'] = None

In [169]:
df = pd.concat([train, test], sort = False)
df.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [170]:
df.shape

(1309, 12)

In [171]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [230]:
df.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

* Embarked
The port in which a passenger has embarked. C - Cherbourg, S - Southampton, Q = Queenstown



In [229]:
xx = df.copy()

In [364]:
#Get Title:

xx['Title'] = xx['Name'].str.split(", ", expand=True)[1].str.split(".", expand=True)[0]
xx.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked Title  Num_Family  
0         A/5 21171   7.2500   NaN        S    Mr           1  
1          PC 17599  71.2833   C85        C   Mrs           1  
2  STON/O2. 3101282   7.9250   NaN        S  Miss           0  
3            113803  53.1000  C123        S   Mrs           1  
4            373450   8.0500   NaN        S    Mr           0

In [232]:
xx.Title.value_counts()

Mr              757
Miss            260
Mrs             197
Master           61
Rev               8
Dr                8
Col               4
Major             2
Ms                2
Mlle              2
Mme               1
Don               1
Jonkheer          1
Dona              1
Capt              1
Sir               1
the Countess      1
Lady              1
Name: Title, dtype: int64

In [235]:
#replacing rare titles with more common ones:

dict1 = {'Mlle':'Miss', 'Major':'Mr', 'Col':'Mr','Sir': "Mr", 'Don':'Mr', 'Mme':'Mrs', 
         'Jonkheer':'Mr','Lady':'Mrs','Capt':'Mr', 'the Countess':'Mrs', 'Ms':'Miss',
        'Dona':'Mrs'}

xx.replace({'Title':dict1}, inplace=True)

In [236]:
xx.Title.value_counts()

Mr        767
Miss      264
Mrs       201
Master     61
Rev         8
Dr          8
Name: Title, dtype: int64

In [342]:

dff = xx.groupby(['Title'])
fill_value = lambda AgeSeries : AgeSeries.fillna(round(eval("np.nan"+'mean')(AgeSeries),1))
xx['Age'] = dff['Age'].transform(fill_value)
        
xx.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked Title  Num_Family  
0         A/5 21171   7.2500   NaN        S    Mr           1  
1          PC 17599  71.2833   C85        C   Mrs           1  
2  STON/O2. 3101282   7.9250   NaN        S  Miss           0  
3            113803  53.1000  C123        S   Mrs           1  
4            373450   8.0500   NaN        S    Mr           0

In [341]:
dfg = xx.groupby(['Pclass'])
fill_value_1 = lambda FareSeries : FareSeries.fillna(round(eval("np.nan"+'mean')(FareSeries),1))
xx['Fare'] = dfg['Fare'].transform(fill_value_1)
        
xx.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked Title  Num_Family  
0         A/5 21171   7.2500   NaN        S    Mr           1  
1          PC 17599  71.2833   C85        C   Mrs           1  
2  STON/O2. 3101282   7.9250   NaN        S  Miss           0  
3            113803  53.1000  C123        S   Mrs           1  
4            373450   8.0500   NaN        S    Mr           0

In [343]:
#xx['Fare'].fillna(xx['Fare'].median(), inplace = True)
xx['Embarked'].fillna(xx['Embarked'].mode()[0], inplace = True)#(method ='backfill', inplace = True)
xx.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked Title  Num_Family  
0         A/5 21171   7.2500   NaN        S    Mr           1  
1          PC 17599  71.2833   C85        C   Mrs           1  
2  STON/O2. 3101282   7.9250   NaN        S  Miss           0  
3            113803  53.1000  C123        S   Mrs           1  
4            373450   8.0500   NaN        S    Mr           0

In [241]:
xx.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age               0
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin          1014
Embarked          0
Title             0
dtype: int64

In [242]:
xx['Num_Family'] = xx['SibSp'] + xx['Parch']
xx.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Title  Num_Family  
0      0         A/5 21171   7.2500   NaN        S    Mr           1  
1      0          PC 17599  71.2833   C85        C   Mrs           1  
2      0  STON/O2. 3101282   7.9250   NaN        S  Miss           0  
3      0            113803  53.1000  C123        S   Mrs           1  
4      0            373450   8.0500   NaN        S    Mr           0

In [244]:
xx.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [245]:
xx['Sex'] = xx['Sex'].astype('category')
xx['Sex'] = xx['Sex'].cat.codes

In [365]:
catty = ['Embarked', 'Title']

df6 = pd.concat([xx, pd.get_dummies(xx[catty])], axis=1)
df6 = df6.drop(catty, axis=1)
df6.head()

PassengerId Survived  Pclass  \
0            1        0       3   
1            2        1       1   
2            3        1       3   
3            4        1       1   
4            5        0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare         ...         Title_Master  Title_Miss  \
0         A/5 21171   7.2500         ...                    0           0   
1          PC 17599  71.2833         ...                    0           0   
2  STON/O2. 3101282   7.9250         ...                    0           1   
3            113803  53.1000         ...                    0           0   
4            373450   8.0500         ...                    0           0   

   Title_Mlle  Title_Mme  Title_Mr  Title_Mrs  Title_Ms  Title_Rev  Title_Sir  \
0           0          0         1          0         0          0          0   
1           0          0         0          1         0          0          0   
2           0          0         0          0         0          0          0   
3           0          0         0          1         0          0          0   
4           0          0         1          0         0          0          0   

   Title_the Countess  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 33 columns]

In [366]:
#too many values missing on cabin 
# we then drop it:

#we also going to drop unnecessary cols:
# PassengerId , 'Ticket'

df6 = df6.drop(['Cabin', 'PassengerId', 'Ticket', 'Name'] , axis = 1)
df6.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Num_Family  Embarked_C  \
0        0       3    1  22.0      1      0   7.2500           1           0   
1        1       1    0  38.0      1      0  71.2833           1           1   
2        1       3    0  26.0      0      0   7.9250           0           0   
3        1       1    0  35.0      1      0  53.1000           1           0   
4        0       3    1  35.0      0      0   8.0500           0           0   

   Embarked_Q         ...          Title_Master  Title_Miss  Title_Mlle  \
0           0         ...                     0           0           0   
1           0         ...                     0           0           0   
2           0         ...                     0           1           0   
3           0         ...                     0           0           0   
4           0         ...                     0           0           0   

   Title_Mme  Title_Mr  Title_Mrs  Title_Ms  Title_Rev  Title_Sir  \
0          0         1          0         0          0          0   
1          0         0          1         0          0          0   
2          0         0          0         0          0          0   
3          0         0          1         0          0          0   
4          0         1          0         0          0          0   

   Title_the Countess  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 29 columns]

In [250]:
# s = [test,train]

# for dataset in s:
#     dataset['Title'] = dataset.Name.str.extract(' ([A-Za-z]+)\.', expand=False)

# pd.crosstab(train['Title'], train['Sex'])

# xx['IsAlone'] = 1 #initialize to yes/1 is alone
# xx['IsAlone'].loc[xx['Num_Family'] > 1] = 0 # now update to no/0 if family size is greater than 1
# xx.head()

#     #Continuous variable bins; qcut vs cut: https://stackoverflow.com/questions/30211923/what-is-the-difference-between-pandas-qcut-and-pandas-cut
#     #Fare Bins/Buckets using qcut or frequency bins: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
# xx['FareBin'] = pd.qcut(xx['Fare'], 4)

#     #Age Bins/Buckets using cut or value bins: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.cut.html
# xx['AgeBin'] = pd.cut(xx['Age'].astype(int), 5)
# xx.head()

#cleanup rare title names
# #print(data1['Title'].value_counts())
# stat_min = 10 #while small is arbitrary, we'll use the common minimum in statistics: http://nicholasjjackson.com/2012/03/08/sample-size-is-10-a-magic-number/
# title_names = (xx['Title'].value_counts() < stat_min) #this will create a true false series with title name as index

# #apply and lambda functions are quick and dirty code to find and replace with fewer lines of code: https://community.modeanalytics.com/python/tutorial/pandas-groupby-and-python-lambda-functions/
# xx['Title'] = xx['Title'].apply(lambda x: 'Misc' if title_names.loc[x] == True else x)
# print(xx['Title'].value_counts())
# print("-"*10)

# label = LabelEncoder()
  
# xx['Sex_Code'] = label.fit_transform(xx['Sex'])
# xx['Embarked_Code'] = label.fit_transform(xx['Embarked'])
# xx['Title_Code'] = label.fit_transform(xx['Title'])
# xx['AgeBin_Code'] = label.fit_transform(xx['AgeBin'])
# xx['FareBin_Code'] = label.fit_transform(xx['FareBin'])

# xx.head()

# #CONVERT: convert objects to category using Label Encoder for train and test/validation dataset

# #define y variable aka target/outcome
# Target = ['Survived']

# #define x variables for original features aka feature selection
# data1_x = ['Sex','Pclass', 'Embarked', 'Title','SibSp', 'Parch', 'Age', 'Fare', 'Num_Family', 'IsAlone'] #pretty name/values for charts
# data1_x_calc = ['Sex_Code','Pclass', 'Embarked_Code', 'Title_Code','SibSp', 'Parch', 'Age', 'Fare'] #coded for algorithm calculation
# data1_xy =  Target + data1_x
# print('Original X Y: ', data1_xy, '\n')


# #define x variables for original w/bin features to remove continuous variables
# data1_x_bin = ['Sex_Code','Pclass', 'Embarked_Code', 'Title_Code', 'Num_Family', 'AgeBin_Code', 'FareBin_Code']
# data1_xy_bin = Target + data1_x_bin
# print('Bin X Y: ', data1_xy_bin, '\n')


# #define x and y variables for dummy features original
# data1_dummy = pd.get_dummies(xx[data1_x])
# data1_x_dummy = data1_dummy.columns.tolist()
# data1_xy_dummy = Target + data1_x_dummy
# print('Dummy X Y: ', data1_xy_dummy, '\n')

In [367]:
train_n = df6[pd.notnull(df6['Survived'])]
test_n = df6[pd.isnull(df6['Survived'])]

In [368]:
train_n.shape, test_n.shape

((891, 29), (418, 29))

In [201]:
# #split train and test data with function defaults
# #random_state -> seed or control random number generator: https://www.quora.com/What-is-seed-in-random-number-generation
# train1_x, test1_x, train1_y, test1_y = train_test_split(train_n[data1_x_calc], train_n[Target], random_state = 0)
# train1_x_bin, test1_x_bin, train1_y_bin, test1_y_bin = train_test_split(train_n[data1_x_bin], train_n[Target] , random_state = 0)
# train1_x_dummy, test1_x_dummy, train1_y_dummy, test1_y_dummy = train_test_split(train_n[data1_x_dummy], train_n[Target], random_state = 0)

In [369]:
X = train_n.drop(['Survived'], axis = 1)
y = train_n['Survived']
Test_d = test_n.drop(['Survived'],axis=1)

In [370]:
X_train, X_test, y_train, y_test = train_test_split(X, y.astype(int), test_size = 0.2, random_state = 42)

In [371]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 28), (179, 28), (712,), (179,))

In [372]:
lm = LogisticRegression()

In [373]:
lm.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [374]:
y_pred = lm.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [216]:
import sklearn
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report

In [375]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       105
           1       0.77      0.77      0.77        74

   micro avg       0.81      0.81      0.81       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



In [376]:
metrics.confusion_matrix(y_test, y_pred)

array([[88, 17],
       [17, 57]], dtype=int64)

In [377]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test, y_pred)))
print('Precision: '+ str( metrics.precision_score(y_test, y_pred, average='weighted')))
print('Recall: '+ str(metrics.recall_score(y_test, y_pred, average='weighted')))
print('F1_Score: '+ str( metrics.f1_score(y_test, y_pred, average='weighted')))

Accuracy: 0.8100558659217877
Precision: 0.8100558659217877
Recall: 0.8100558659217877
F1_Score: 0.8100558659217877


In [220]:
tst = lm.predict(Test_d)
tst

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [221]:
df_lm = pd.DataFrame({'PassengerId': test['PassengerId'],'Survived': tst})
df_lm.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [222]:
df_lm.to_csv('lm_enginee.csv', index = False)

In [378]:
rf = RandomForestClassifier(random_state = 0, n_estimators = 2000 ,min_samples_leaf=2)

In [379]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=2000, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [380]:
y_pred_rf = rf.predict(X_test)
y_pred_rf

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [381]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86       105
           1       0.82      0.78      0.80        74

   micro avg       0.84      0.84      0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179



In [382]:
metrics.confusion_matrix(y_test, y_pred_rf)

array([[92, 13],
       [16, 58]], dtype=int64)

In [383]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test, y_pred_rf)))
print('Precision: '+ str( metrics.precision_score(y_test, y_pred_rf, average='weighted')))
print('Recall: '+ str(metrics.recall_score(y_test, y_pred_rf, average='weighted')))
print('F1_Score: '+ str( metrics.f1_score(y_test, y_pred_rf, average='macro')))

Accuracy: 0.8379888268156425
Precision: 0.8374030651943941
Recall: 0.8379888268156425
F1_Score: 0.831924882629108


In [338]:
tst_rf = rf.predict(Test_d)
tst_rf

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [339]:
df_lm = pd.DataFrame({'PassengerId': test['PassengerId'],'Survived': tst_rf})
df_lm.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [340]:
df_lm.to_csv('rf_rand0.csv', index = False)